export { addMovie } from './addMovie.js'
export { deleteMovie } from './deleteMovie.js'
export { getMovie } from './getMovie.js'
export { updateMovie } from './updateMovie.js'
export { getAllMovies } from './getAllMovies.js'
